### ISSUE TITLE
[Suggestion] PaySafeCard Support

### ISSUE THREAD

**Issue by kacperleague9** [TimvanDijkhuizen/MinecraftCommerce#1]
Hey, my suggestion is adding manual paysafecard gateway. If user provides a code, moderators of the server will check the code and deny or accept it.

Second option is adding support for credit card payments

**Comment by TimvanDijkhuizen** [comment]
Thanks for your suggestion! 

PayPal was my first choice because I think it will be the most popular gateway, but I do plan on adding more options later. Because of security reasons I will always let a payment provider handle the payment, so if you know any good payment providers that support credit card let me know.

Since the plugin has just been released I am going to wait a little while before adding big new features, this so I can focus on fixing bugs and improving the documentation. If you are a developer and want to add a custom gateway type you can do that with a plugin. I will be creating better documentation for developers asap.

**Comment by TimvanDijkhuizen** [comment]
I personally don't use PayPal a lot so I only just found out about this but PayPal also allows you to add bank accounts and (credit) cards which can be used to pay with.

**Comment by kacperleague9** [comment]
Hey, i suggested manual because it doesnt require you to be 18+. It's very popular payment method in my country because people can go to shop and buy it easily. Most of players dont have paypal or credit card because they are not 15+

**Comment by kacperleague9** [comment]
a good payment provider is hotpay

**Comment by kacperleague9** [comment]
5 months passed, any info about it 😂?

**Comment by TimvanDijkhuizen** [comment]
Sorry for my inactivity. I've been really busy with school and work the past months. I will try to start working on a gateway that supports Paysafecard later this week.

**Comment by TimvanDijkhuizen** [comment]
I'm currently working on a Mollie gateway plugin, which supports PaysafeCard. It shouldn't take too much time to implement but due to my limited time, I cannot say when this gateway will be finished.

**Comment by tim-van-dijkhuizen** [comment]
Once again, sorry for my inactivity.

Due to lack of time and motivation, I will no longer develop new major features. As of now, I will still be fixing bugs, updating the plugin and making minor improvements. This project was started as a proof of concept and even though I'm happy with the results, there isn't much people who can use this plugin. The plugin is open-source, so feel free to continue developing this project for your own personal use.

Thank you very much for your involvement and feedback, I really appreciate it :)
